// <auto-generated />
namespace OliveiraSuporte.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BdInicial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206140156262_BdInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy/L4jIv6uz1elXVbT7+qi3Kj9LjssgIl9d5ef6eiO08BGIf2S6p01NCrr1+c73KuePPPjopi3zZ5n4javZ75dfBB/TRy7pa5XV7/So/D189m32U3g1fv9t9377dfxW4fPbR2bK9t/dR+mJdltmkpA/Os7LJP0pXnz563VZ1/nm+zOuszWcvs7bNa5qns1nOY1GaPFp9ejuyPLy7swey3M2Wy6rNWpr0Hv4dbF9Ui9wg+rqtiX8+Sp8V7/LZ83x50c4tsl9k78wn94mJvloWxG30Tluv88jYbu70dLGq8yZ7z77p1w2dy9+b+z5dZOC8H3Kvb/IyP6+W70vqzR3fitbPq4ti+Z7d7n3wDL/Ol/P3ndsP7/V0OcvrfFq9Z8fvTeXHd52u6WsgUottVpBMK1ZPJyfVYr3sqCFp+zpvQ7XRfJQ62KIZx0aPRXGwvTnte1fUr1HTdwf09OMvstWK6OPpbf0kfS1K+2T79fur5YXAuDttItrZYmt7Ig2YXeSdb6lrwvRZUTft06zNJhlm4GS26DW7gbamlw6Ju/rfUdy8gN/lpZjhsjPSAeQo+IwGtaAmPD4dHeEzYJP03dfTrMzqYXNyUpXrxfIGA7UJlih7H4x88n4QrObuArJf3B6eamMfkn50exhOt/pg3Ke3h6S60gejH90ehmo+H4Z+dHsYTo8FhLGf9iE9vtthvC6LexpLW3bcmq7MbFI13Sa2d6tyOqrlsYr5zX5iT+6lyUcpkeiymEHmX183bb4Yo8H49S8qRRJcgy+yZXGeN+2b6m0On5fU0td3NK1H1TSz8v8T3mYBWtzoV76nYfW9xOVlVk/nWd3zCb8GzI4TaEBvLbJ3d97XxQocuw+C5FTHDcBuNc7AAYsSb+/9iRf4V98U0K779D7jfj+XqG/dQ8QGnKNNvpHoic8+mk2Av+D5oY5TX2s9vuvHwI+f5k1x4UAgIl7mU8RdDqhpc7Y8rwzBaWQ+RqZJZz6+yNtsRgQ6rtviPJu29PU0bxp2aX8yK9fM9JN8drb8ct2u1u1x0+SLSXntj/fx3c39s3cY4vz4yxX+8tT01x8CoVnQEPIvl0/WRTmzeD+LcNAACPCKqjLCilx6AndxbSG96Nn4IUBKvqf5Kl9CEb7JF6uSgDVfLl9nl/kwbjfTMKTY46dFdlFnC5+C8omR3ox69rqgDvw3XH/0J7ErJWCO/p8AAAD//yriZaj1EQAA"; }
        }
    }
}
